/**
 * LLM-as-judge helpers for everest-stack eval pipeline.
 * Ported from garrytan/gstack test/helpers/llm-judge.ts
 * Adapted: Node.js (not Bun), foreclosure domain scoring.
 *
 * Requires: ANTHROPIC_API_KEY env var
 * Cost: ~$0.15/run via claude-sonnet-4-6
 */

const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY;
const MODEL = "claude-sonnet-4-6";
const MAX_TOKENS = 1024;

/**
 * Call Claude as a judge. Returns parsed JSON.
 * Retries once on 429.
 */
async function callJudge(prompt) {
  if (!ANTHROPIC_API_KEY) {
    throw new Error("ANTHROPIC_API_KEY required for LLM judge evals");
  }

  const makeRequest = () =>
    fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": ANTHROPIC_API_KEY,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: MODEL,
        max_tokens: MAX_TOKENS,
        messages: [{ role: "user", content: prompt }],
      }),
    });

  let response;
  try {
    response = await makeRequest();
    if (response.status === 429) {
      await new Promise((r) => setTimeout(r, 1500));
      response = await makeRequest();
    }
  } catch (err) {
    throw new Error(`Judge API call failed: ${err.message}`);
  }

  const data = await response.json();
  if (data.error) throw new Error(`Judge API error: ${data.error.message}`);

  const text =
    data.content && data.content[0] && data.content[0].type === "text"
      ? data.content[0].text
      : "";

  const jsonMatch = text.match(/\{[\s\S]*\}/);
  if (!jsonMatch)
    throw new Error(`Judge returned non-JSON: ${text.slice(0, 200)}`);
  return JSON.parse(jsonMatch[0]);
}

/**
 * Score a SKILL.md document on quality dimensions (1-5 scale).
 * Adapted for foreclosure deal analysis skills.
 */
async function judgeSkillQuality(skillName, content) {
  return callJudge(`You are evaluating the quality of an AI agent skill definition for foreclosure investing.

The agent reads this SKILL.md to learn how to evaluate foreclosure deals, audit lien priority,
or perform property analysis in Brevard County, Florida.

The skill must enable the agent to:
1. Understand the domain-specific process (foreclosure law, lien priority, auction procedures)
2. Ask the right questions in the right order
3. Produce accurate, evidence-based recommendations (BID/REVIEW/SKIP)
4. Never make assumptions without verification

Rate the skill "${skillName}" on five dimensions (1-5 scale):

- **clarity** (1-5): Can the agent understand each phase and what to do?
- **completeness** (1-5): Are all critical checks covered? Would the agent miss anything dangerous?
- **domain_accuracy** (1-5): Is the Florida foreclosure law and procedure correct?
- **anti_sycophancy** (1-5): Does the skill enforce honest, evidence-based responses over optimism?
- **actionability** (1-5): Can the agent produce a concrete BID/REVIEW/SKIP recommendation with math?

Scoring guide:
- 5: Excellent — production-ready, covers edge cases, legally accurate
- 4: Good — minor gaps an experienced investor could fill
- 3: Adequate — works for common cases, misses edge cases
- 2: Poor — significant gaps that could cause financial loss
- 1: Dangerous — would lead to bad investment decisions

Respond with ONLY valid JSON:
{"clarity": N, "completeness": N, "domain_accuracy": N, "anti_sycophancy": N, "actionability": N, "overall": N, "reasoning": "brief explanation", "critical_gaps": ["gap1", "gap2"]}

where "overall" is the average of all five scores rounded to one decimal.

SKILL.md content:

${content}`);
}

/**
 * Evaluate a deal evaluation report against expected outputs.
 * Used for end-to-end testing of /deal-office-hours.
 */
async function judgeDealEvaluation(scenario, report) {
  return callJudge(`You are evaluating a foreclosure deal evaluation report generated by an AI agent.

SCENARIO (ground truth):
${JSON.stringify(scenario, null, 2)}

AGENT'S DEAL EVALUATION REPORT:
${report}

Evaluate whether the agent:
1. Asked all 6 forcing questions
2. Correctly identified the foreclosure type
3. Applied the max bid formula correctly
4. Made the right BID/REVIEW/SKIP recommendation given the scenario
5. Flagged all risk factors present in the ground truth
6. Did NOT invent data not present in the scenario

Respond with ONLY valid JSON:
{
  "questions_asked": 6,
  "questions_quality": N,
  "foreclosure_type_correct": true,
  "max_bid_formula_correct": true,
  "recommendation_correct": true,
  "risk_flags_detected": ["flag1"],
  "risk_flags_missed": ["flag2"],
  "invented_data": false,
  "overall_score": N,
  "reasoning": "brief explanation"
}

where N is 1-5 scale, questions_quality rates depth of follow-up pushback.`);
}

/**
 * Evaluate a lien audit report against known lien structure.
 */
async function judgeLienAudit(groundTruth, report) {
  return callJudge(`You are evaluating a lien priority audit report generated by an AI agent.

GROUND TRUTH (actual recorded instruments):
${JSON.stringify(groundTruth, null, 2)}

AGENT'S LIEN AUDIT REPORT:
${report}

Evaluate whether the agent:
1. Correctly classified the foreclosure type
2. Found all liens in the ground truth
3. Correctly determined which liens survive vs. are extinguished
4. Calculated the total acquisition cost accurately
5. Made the correct CLEARED/NEEDS_VERIFICATION/DO_NOT_BID recommendation
6. Did NOT miss any senior liens that would cause financial loss

Respond with ONLY valid JSON:
{
  "foreclosure_type_correct": true,
  "liens_found": N,
  "liens_total": N,
  "priority_analysis_correct": true,
  "surviving_liens_correct": true,
  "total_cost_accurate": true,
  "recommendation_correct": true,
  "missed_critical_liens": [],
  "false_liens": [],
  "confidence_rating_appropriate": true,
  "overall_score": N,
  "reasoning": "brief explanation"
}

CRITICAL: A missed senior mortgage on an HOA foreclosure is a CATASTROPHIC error (score 1).
A missed tax certificate is a SERIOUS error (score 2). Missing a code enforcement lien
in PRE-BID mode is acceptable (score 4) since it's deferred to POST-ACQUISITION.`);
}

module.exports = {
  callJudge,
  judgeSkillQuality,
  judgeDealEvaluation,
  judgeLienAudit,
};
